export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const BASE_API_URL = 'http://localhost:5000';
export const GET_ERRORS = 'GET_ERRORS';
export const RESET_ERRORS = 'RESET_ERRORS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE'; //TODO : DELETE
export const GET_TASKS = 'GET_TASKS';
// export const TASKS_DOING = 'TASKS_DOING';
// export const TASKS_DONE = 'TASKS_DONE'; //not yet approved by manager